name: Tests

on: pull_request

jobs:
  cypress:
    name: cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v1
  jest:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Run Jest
        run: react-scripts test --verbose ./src/jest/*
