name: Tests

on: 
  pull_request

jobs:
  # cypress:
  #   name: Test with Cypress
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         start: yarn start
  # jest:
  #   name: Test with Jest
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Run Jest
  #       run: yarn jest
  dingdong:
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.package }} (${{ matrix.platform }})
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        package: [one, two]
    steps:
    - name: only if two and ubunutu
      if: ${{ matrix.package == two }}
      run: echo it is two